uavs:
  - {name: UAV6, ip: 127.0.0.1, port_offset: 0}
  - {name: UAV7, ip: 127.0.0.1, port_offset: 100}
  - {name: UAV8, ip: 127.0.0.1, port_offset: 200}
  - {name: UAV9, ip: 127.0.0.1, port_offset: 300}

topics:
  - {name: mavros/state,                   type: mavros_msgs/State}
  - {name: mavros/time_reference,          type: sensor_msgs/TimeReference}
  - {name: mavros/global_position/global,  type: sensor_msgs/NavSatFix}
  - {name: mavros/local_position/odom,     type: nav_msgs/Odometry}
  - {name: mavros/rc/in,                   type: mavros_msgs/RCIn}
  - {name: leader_fix_origin,              type: sensor_msgs/NavSatFix}
  - {name: chatter,                        type: std_msgs/String}

max_freq: 50
base_port: 3000

topology:
  UAV6: [UAV7, UAV8, UAV9]
  UAV7: [UAV6, UAV8, UAV9]
  UAV8: [UAV6, UAV7, UAV9]
  UAV9: [UAV6, UAV7, UAV8]
